// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgN4pzBS-yTQKlvnyiWG_O3rCw3NVP7mI',
    appId: '1:576851884571:web:54649eef939f6102a416be',
    messagingSenderId: '576851884571',
    projectId: 'life-development-10dfe',
    authDomain: 'life-development-10dfe.firebaseapp.com',
    storageBucket: 'life-development-10dfe.appspot.com',
    measurementId: 'G-4G12X0CG47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Z21ATT-krSb6EPH4djeTOuuQNb_bDdA',
    appId: '1:576851884571:android:020bc5ce03e40518a416be',
    messagingSenderId: '576851884571',
    projectId: 'life-development-10dfe',
    storageBucket: 'life-development-10dfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu7Ez6pu0IWbaFL0OfOSWtxnN_RjR1Q0o',
    appId: '1:576851884571:ios:309307fde8fea19aa416be',
    messagingSenderId: '576851884571',
    projectId: 'life-development-10dfe',
    storageBucket: 'life-development-10dfe.appspot.com',
    iosBundleId: 'com.lifefrontend.beta',
  );
}
