// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN0vDtLpArneRn5fTqmTGvL64HMgehxAg',
    appId: '1:631460848606:web:1cd7641fd66c7aa38e334f',
    messagingSenderId: '631460848606',
    projectId: 'life-production-a565d',
    authDomain: 'life-production-a565d.firebaseapp.com',
    storageBucket: 'life-production-a565d.appspot.com',
    measurementId: 'G-JQ2XY4L71G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzU8ZIppMW1OgNTXPTL5pIeaKGH8x_rMw',
    appId: '1:631460848606:android:d1572dc6478ef1a38e334f',
    messagingSenderId: '631460848606',
    projectId: 'life-production-a565d',
    storageBucket: 'life-production-a565d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPbAUutPtSH_3gTXfzmgNG3tLY_3wFljg',
    appId: '1:631460848606:ios:48d90faf71375ff98e334f',
    messagingSenderId: '631460848606',
    projectId: 'life-production-a565d',
    storageBucket: 'life-production-a565d.appspot.com',
    iosBundleId: 'com.lifefrontend.beta',
  );
}
