// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByYBIXidilQpimB40-xCgrfj0o8ZrR2Fw',
    appId: '1:246380261345:web:744e64a586d502e67eeca0',
    messagingSenderId: '246380261345',
    projectId: 'life-beta-9a17e',
    authDomain: 'life-beta-9a17e.firebaseapp.com',
    storageBucket: 'life-beta-9a17e.appspot.com',
    measurementId: 'G-Q6FFH9QTYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByIQ0KzSo3kJoj7oTSIJNzo-BbSjHpWd8',
    appId: '1:246380261345:android:be2c6d65a16124fe7eeca0',
    messagingSenderId: '246380261345',
    projectId: 'life-beta-9a17e',
    storageBucket: 'life-beta-9a17e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhhpjyWS9UnG3w0aC-2j_we3P7EArl9Ys',
    appId: '1:246380261345:ios:fecc12ceec3a07f07eeca0',
    messagingSenderId: '246380261345',
    projectId: 'life-beta-9a17e',
    storageBucket: 'life-beta-9a17e.appspot.com',
    iosBundleId: 'com.lifefrontend.beta',
  );
}
