// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANBq15XJlEzWBgvWR9WgZskUSGF_KvkdM',
    appId: '1:19151158311:web:6f937eb732d3e54316e202',
    messagingSenderId: '19151158311',
    projectId: 'life-development-44e4b',
    authDomain: 'life-development-44e4b.firebaseapp.com',
    storageBucket: 'life-development-44e4b.appspot.com',
    measurementId: 'G-Y85XTPVCVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzwNGZ2aNzSqoJbTB97mxbHFtfhlgiW1s',
    appId: '1:19151158311:android:bee337fa3386288316e202',
    messagingSenderId: '19151158311',
    projectId: 'life-development-44e4b',
    storageBucket: 'life-development-44e4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZRvp-KCH8th_peyE5hLSchk7TqYFNjh4',
    appId: '1:19151158311:ios:e27b82cd34247ec816e202',
    messagingSenderId: '19151158311',
    projectId: 'life-development-44e4b',
    storageBucket: 'life-development-44e4b.appspot.com',
    iosBundleId: 'com.phatmenghor.lifefrontend.beta',
  );
}
